//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MBNCSUtil {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MBNCSUtil.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file was not found by Battle.net..
        /// </summary>
        internal static string bnftp_filenotfound {
            get {
                return ResourceManager.GetString("bnftp_filenotfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Starcraft, Starcraft: Brood War, Diablo II Retail, Diablo II: the Lord of Destruction, and Warcraft II: Battle.net Edition (STAR, SEXP, D2DV, D2XP, and W2BN, respectively) can use BnFTP version 1..
        /// </summary>
        internal static string bnftp_ver1invalidProduct {
            get {
                return ResourceManager.GetString("bnftp_ver1invalidProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Warcraft III: the Reign of Chaos, and Warcraft III: the Frozen Throne (WAR3 and W3XP, respectively) can use BnFTP version 2..
        /// </summary>
        internal static string bnftp_ver2invalidProduct {
            get {
                return ResourceManager.GetString("bnftp_ver2invalidProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value specified for the CD key is null..
        /// </summary>
        internal static string cdKeyArgNull {
            get {
                return ResourceManager.GetString("cdKeyArgNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction of MPQ number is not supported on Lockdown MPQs.  The entire Lockdown DLL file must be passed into the Lockdown CheckRevision function.  See the CheckRevision class documentation for more information..
        /// </summary>
        internal static string crevExtrMpqNum_NoLockdown {
            get {
                return ResourceManager.GetString("crevExtrMpqNum_NoLockdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file name cannot be null..
        /// </summary>
        internal static string crExeFileNull {
            get {
                return ResourceManager.GetString("crExeFileNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a list of exactly three files for the revision check..
        /// </summary>
        internal static string crFileListInvalid {
            get {
                return ResourceManager.GetString("crFileListInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a 3-file list for the revision check..
        /// </summary>
        internal static string crFileListNull {
            get {
                return ResourceManager.GetString("crFileListNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the MPQ version file must be greater than 7 characters long..
        /// </summary>
        internal static string crMpqNameArgShort {
            get {
                return ResourceManager.GetString("crMpqNameArgShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MPQ name parameter cannot be null..
        /// </summary>
        internal static string crMpqNameNull {
            get {
                return ResourceManager.GetString("crMpqNameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value string parameter cannot be null for a revision check..
        /// </summary>
        internal static string crValstringNull {
            get {
                return ResourceManager.GetString("crValstringNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D2DV.
        /// </summary>
        internal static string d2dv {
            get {
                return ResourceManager.GetString("d2dv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D2XP.
        /// </summary>
        internal static string d2xp {
            get {
                return ResourceManager.GetString("d2xp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified data buffer was null..
        /// </summary>
        internal static string dataNull {
            get {
                return ResourceManager.GetString("dataNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified encoding parameter was null..
        /// </summary>
        internal static string encNull {
            get {
                return ResourceManager.GetString("encNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1:d1}/{2:d2}/{3:d2} {4:d2}:{5:d2}:{6:d2} {7}.
        /// </summary>
        internal static string exeInfoFmt {
            get {
                return ResourceManager.GetString("exeInfoFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file was not found..
        /// </summary>
        internal static string fileNotFound {
            get {
                return ResourceManager.GetString("fileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified value for the local file name was null..
        /// </summary>
        internal static string fileNull {
            get {
                return ResourceManager.GetString("fileNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CD key must be a valid 13-, 16-, or 26-character key..
        /// </summary>
        internal static string invalidCdKeyGeneral {
            get {
                return ResourceManager.GetString("invalidCdKeyGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot calculate the key hash on an invalid key..
        /// </summary>
        internal static string invalidCdKeyHashed {
            get {
                return ResourceManager.GetString("invalidCdKeyHashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CD key specified is not a valid Starcraft CD key..
        /// </summary>
        internal static string invalidCdKeySc {
            get {
                return ResourceManager.GetString("invalidCdKeySc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CD key specified is not a valid Warcraft II/Diablo II/Lord of Destruction CD key..
        /// </summary>
        internal static string invalidCdKeyWar2 {
            get {
                return ResourceManager.GetString("invalidCdKeyWar2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CD key specified is not a valid Warcraft III/Frozen Throne CD key..
        /// </summary>
        internal static string invalidCdKeyWar3 {
            get {
                return ResourceManager.GetString("invalidCdKeyWar3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MPQ file was not able to be opened in the specified mode..
        /// </summary>
        internal static string mpq_badOpenMode {
            get {
                return ResourceManager.GetString("mpq_badOpenMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file could not be found in the MPQ archive..
        /// </summary>
        internal static string mpq_fileNotFound {
            get {
                return ResourceManager.GetString("mpq_fileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MPQ file is corrupt..
        /// </summary>
        internal static string mpq_mpqArchiveCorrupt {
            get {
                return ResourceManager.GetString("mpq_mpqArchiveCorrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown MPQ API error: {0}.
        /// </summary>
        internal static string mpq_UnknownErrorType {
            get {
                return ResourceManager.GetString("mpq_UnknownErrorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the MPQ file cannot be null..
        /// </summary>
        internal static string mpqFilePathArgNull {
            get {
                return ResourceManager.GetString("mpqFilePathArgNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is insufficient space in the data buffer for the account creation packet..
        /// </summary>
        internal static string nlsAcctCreateSpace {
            get {
                return ResourceManager.GetString("nlsAcctCreateSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is insufficient space in the data buffer for the account login packet..
        /// </summary>
        internal static string nlsAcctLoginSpace {
            get {
                return ResourceManager.GetString("nlsAcctLoginSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is insufficient space in the data buffer for the account login proof packet..
        /// </summary>
        internal static string nlsLoginProofSpace {
            get {
                return ResourceManager.GetString("nlsLoginProofSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The salt value was not 32 bytes..
        /// </summary>
        internal static string nlsSalt32 {
            get {
                return ResourceManager.GetString("nlsSalt32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server key was not 32 bytes..
        /// </summary>
        internal static string nlsServerKey32 {
            get {
                return ResourceManager.GetString("nlsServerKey32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server proof value must be exactly 20 bytes..
        /// </summary>
        internal static string nlsServerProof20 {
            get {
                return ResourceManager.GetString("nlsServerProof20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server signature must be exactly 128 bytes..
        /// </summary>
        internal static string nlsSrvSig128 {
            get {
                return ResourceManager.GetString("nlsSrvSig128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object you attempted to access has not yet been initialized.  You must call the Initialize method on the object before it can be used..
        /// </summary>
        internal static string notInitialized {
            get {
                return ResourceManager.GetString("notInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An object was already initiated at the call for initiation..
        /// </summary>
        internal static string objAlreadyInited {
            get {
                return ResourceManager.GetString("objAlreadyInited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An object was not initialized prior to use..
        /// </summary>
        internal static string objNotInited {
            get {
                return ResourceManager.GetString("objNotInited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cdKey.
        /// </summary>
        internal static string param_cdKey {
            get {
                return ResourceManager.GetString("param_cdKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data.
        /// </summary>
        internal static string param_data {
            get {
                return ResourceManager.GetString("param_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enc.
        /// </summary>
        internal static string param_enc {
            get {
                return ResourceManager.GetString("param_enc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fileName.
        /// </summary>
        internal static string param_fileName {
            get {
                return ResourceManager.GetString("param_fileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to len.
        /// </summary>
        internal static string param_len {
            get {
                return ResourceManager.GetString("param_len", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mpqFilePath.
        /// </summary>
        internal static string param_mpqFilePath {
            get {
                return ResourceManager.GetString("param_mpqFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to productId.
        /// </summary>
        internal static string param_productId {
            get {
                return ResourceManager.GetString("param_productId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to salt.
        /// </summary>
        internal static string param_salt {
            get {
                return ResourceManager.GetString("param_salt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to serverKey.
        /// </summary>
        internal static string param_serverKey {
            get {
                return ResourceManager.GetString("param_serverKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to str.
        /// </summary>
        internal static string param_str {
            get {
                return ResourceManager.GetString("param_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value.
        /// </summary>
        internal static string param_value {
            get {
                return ResourceManager.GetString("param_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEXP.
        /// </summary>
        internal static string sexp {
            get {
                return ResourceManager.GetString("sexp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STAR.
        /// </summary>
        internal static string star {
            get {
                return ResourceManager.GetString("star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StormLib32 {
            get {
                object obj = ResourceManager.GetObject("StormLib32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] StormLib64 {
            get {
                object obj = ResourceManager.GetObject("StormLib64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified stream is null..
        /// </summary>
        internal static string streamNull {
            get {
                return ResourceManager.GetString("streamNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified string is null..
        /// </summary>
        internal static string strNull {
            get {
                return ResourceManager.GetString("strNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String length was too long; max length {0}..
        /// </summary>
        internal static string strTooLongFmt {
            get {
                return ResourceManager.GetString("strTooLongFmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified parameter must be greater than zero (0)..
        /// </summary>
        internal static string valMustBeGTZero {
            get {
                return ResourceManager.GetString("valMustBeGTZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W2BN.
        /// </summary>
        internal static string w2bn {
            get {
                return ResourceManager.GetString("w2bn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W3XP.
        /// </summary>
        internal static string w3xp {
            get {
                return ResourceManager.GetString("w3xp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAR3.
        /// </summary>
        internal static string war3 {
            get {
                return ResourceManager.GetString("war3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot hash more than 1024 bytes..
        /// </summary>
        internal static string xshaMaxHash1024 {
            get {
                return ResourceManager.GetString("xshaMaxHash1024", resourceCulture);
            }
        }
    }
}
