'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace AtlasV.Localization

    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Public Class Resources

        Private Shared resourceMan As Global.System.Resources.ResourceManager

        Private Shared resourceCulture As Global.System.Globalization.CultureInfo

        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>
        Friend Sub New()
            MyBase.New
        End Sub

        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property

        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = Value
            End Set
        End Property

        '''<summary>
        '''  Looks up a localized string similar to That account is already logged on..
        '''</summary>
        Public Shared ReadOnly Property AccountIsAlreadyLoggedOn() As String
            Get
                Return ResourceManager.GetString("AccountIsAlreadyLoggedOn", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Added {friend} to your friends list..
        '''</summary>
        Public Shared ReadOnly Property AddedFriend() As String
            Get
                Return ResourceManager.GetString("AddedFriend", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Who do you want to add?.
        '''</summary>
        Public Shared ReadOnly Property AddFriendEmptyTarget() As String
            Get
                Return ResourceManager.GetString("AddFriendEmptyTarget", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to {user} was disconnected..
        '''</summary>
        Public Shared ReadOnly Property AdminDisconnectCommand() As String
            Get
                Return ResourceManager.GetString("AdminDisconnectCommand", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Admin Command List:.
        '''</summary>
        Public Shared ReadOnly Property AdminHelpCommand() As String
            Get
                Return ResourceManager.GetString("AdminHelpCommand", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Forcefully moved {user} to the channel {channel}..
        '''</summary>
        Public Shared ReadOnly Property AdminMoveUserCommand() As String
            Get
                Return ResourceManager.GetString("AdminMoveUserCommand", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to An {exception} occurred while reloading the server configuration. Server stability is now at risk, notify a system administrator immediately..
        '''</summary>
        Public Shared ReadOnly Property AdminReloadCommandFailure() As String
            Get
                Return ResourceManager.GetString("AdminReloadCommandFailure", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to The server configuration has been reloaded..
        '''</summary>
        Public Shared ReadOnly Property AdminReloadCommandSuccess() As String
            Get
                Return ResourceManager.GetString("AdminReloadCommandSuccess", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to The server shutdown was cancelled..
        '''</summary>
        Public Shared ReadOnly Property AdminShutdownCommandCancelled() As String
            Get
                Return ResourceManager.GetString("AdminShutdownCommandCancelled", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to There is no shutdown event scheduled for the server..
        '''</summary>
        Public Shared ReadOnly Property AdminShutdownCommandNotScheduled() As String
            Get
                Return ResourceManager.GetString("AdminShutdownCommandNotScheduled", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Unable to parse your grace period in seconds, please see https://bit.ly/34Sgl2w.
        '''</summary>
        Public Shared ReadOnly Property AdminShutdownCommandParseError() As String
            Get
                Return ResourceManager.GetString("AdminShutdownCommandParseError", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to The server shutdown was scheduled..
        '''</summary>
        Public Shared ReadOnly Property AdminShutdownCommandScheduled() As String
            Get
                Return ResourceManager.GetString("AdminShutdownCommandScheduled", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Set {user}&apos;s active channel flags to {flags}..
        '''</summary>
        Public Shared ReadOnly Property AdminSpoofUserFlagsCommand() As String
            Get
                Return ResourceManager.GetString("AdminSpoofUserFlagsCommand", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Unable to parse the flags into an unsigned 32-bit integer.
        '''Supported number prefixes:
        '''- Binary: 0b, 0B, &amp;b, &amp;B
        '''- Hex: 0x, 0X, &amp;h, &amp;H
        '''- Octal: 0
        '''- Decimal: Any whole number, not prefixed with zero (octal indication)
        '''Example: 0x10 = 16 decimal.
        '''</summary>
        Public Shared ReadOnly Property AdminSpoofUserFlagsCommandBadValue() As String
            Get
                Return ResourceManager.GetString("AdminSpoofUserFlagsCommandBadValue", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Set {user}&apos;s game to {game}..
        '''</summary>
        Public Shared ReadOnly Property AdminSpoofUserGameCommand() As String
            Get
                Return ResourceManager.GetString("AdminSpoofUserGameCommand", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Unable to parse the game value into a product.
        '''Examples: SEXP, pxes.
        '''</summary>
        Public Shared ReadOnly Property AdminSpoofUserGameCommandBadValue() As String
            Get
                Return ResourceManager.GetString("AdminSpoofUserGameCommandBadValue", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Set {name1}&apos;s name to {name2}..
        '''</summary>
        Public Shared ReadOnly Property AdminSpoofUserNameCommand() As String
            Get
                Return ResourceManager.GetString("AdminSpoofUserNameCommand", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Unacceptable new name for target..
        '''</summary>
        Public Shared ReadOnly Property AdminSpoofUserNameCommandBadValue() As String
            Get
                Return ResourceManager.GetString("AdminSpoofUserNameCommandBadValue", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Set {user}&apos;s ping to {ping}ms..
        '''</summary>
        Public Shared ReadOnly Property AdminSpoofUserPingCommand() As String
            Get
                Return ResourceManager.GetString("AdminSpoofUserPingCommand", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Unable to parse the ping into an unsigned 32-bit integer.
        '''Supported number prefixes:
        '''- Binary: 0b, 0B, &amp;b, &amp;B
        '''- Hex: 0x, 0X, &amp;h, &amp;H
        '''- Octal: 0
        '''- Decimal: Any whole number, not prefixed with zero (octal indication)
        '''Example: 0x10 = 16 decimal.
        '''</summary>
        Public Shared ReadOnly Property AdminSpoofUserPingCommandBadValue() As String
            Get
                Return ResourceManager.GetString("AdminSpoofUserPingCommandBadValue", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to {friend} is already in your friends list..
        '''</summary>
        Public Shared ReadOnly Property AlreadyAddedFriend() As String
            Get
                Return ResourceManager.GetString("AlreadyAddedFriend", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to {friend} is not in your friends list..
        '''</summary>
        Public Shared ReadOnly Property AlreadyRemovedFriend() As String
            Get
                Return ResourceManager.GetString("AlreadyRemovedFriend", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to You are no longer marked as away..
        '''</summary>
        Public Shared ReadOnly Property AwayCommandOff() As String
            Get
                Return ResourceManager.GetString("AwayCommandOff", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to You are now marked as being away..
        '''</summary>
        Public Shared ReadOnly Property AwayCommandOn() As String
            Get
                Return ResourceManager.GetString("AwayCommandOn", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to {user} is away ({awayMessage}).
        '''</summary>
        Public Shared ReadOnly Property AwayCommandStatus() As String
            Get
                Return ResourceManager.GetString("AwayCommandStatus", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to You are away ({awayMessage}).
        '''</summary>
        Public Shared ReadOnly Property AwayCommandStatusSelf() As String
            Get
                Return ResourceManager.GetString("AwayCommandStatusSelf", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Backstage.
        '''</summary>
        Public Shared ReadOnly Property Backstage() As String
            Get
                Return ResourceManager.GetString("Backstage", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Battle.net administrator.
        '''</summary>
        Public Shared ReadOnly Property BattlenetAdministrator() As String
            Get
                Return ResourceManager.GetString("BattlenetAdministrator", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Battle.net representative.
        '''</summary>
        Public Shared ReadOnly Property BattlenetRepresentative() As String
            Get
                Return ResourceManager.GetString("BattlenetRepresentative", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Blizzard administrator.
        '''</summary>
        Public Shared ReadOnly Property BlizzardAdministrator() As String
            Get
                Return ResourceManager.GetString("BlizzardAdministrator", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Blizzard representative.
        '''</summary>
        Public Shared ReadOnly Property BlizzardRepresentative() As String
            Get
                Return ResourceManager.GetString("BlizzardRepresentative", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Welcome to {realm}!
        '''This server is hosted by {host}.
        '''{serverStats}.
        '''</summary>
        Public Shared ReadOnly Property ChannelFirstJoinGreeting() As String
            Get
                Return ResourceManager.GetString("ChannelFirstJoinGreeting", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to This channel does not have chat privileges..
        '''</summary>
        Public Shared ReadOnly Property ChannelIsChatRestricted() As String
            Get
                Return ResourceManager.GetString("ChannelIsChatRestricted", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to That channel is full..
        '''</summary>
        Public Shared ReadOnly Property ChannelIsFull() As String
            Get
                Return ResourceManager.GetString("ChannelIsFull", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to This channel is now private, new users are rejected..
        '''</summary>
        Public Shared ReadOnly Property ChannelIsNowPrivate() As String
            Get
                Return ResourceManager.GetString("ChannelIsNowPrivate", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to This channel is now public, new users are allowed..
        '''</summary>
        Public Shared ReadOnly Property ChannelIsNowPublic() As String
            Get
                Return ResourceManager.GetString("ChannelIsNowPublic", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to That channel is restricted..
        '''</summary>
        Public Shared ReadOnly Property ChannelIsRestricted() As String
            Get
                Return ResourceManager.GetString("ChannelIsRestricted", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to The upper user limit for this channel was changed to {maxUsers}..
        '''</summary>
        Public Shared ReadOnly Property ChannelMaxUsersChanged() As String
            Get
                Return ResourceManager.GetString("ChannelMaxUsersChanged", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to That channel does not exist.
        '''(If you are trying to search for a user, use the /whois command.).
        '''</summary>
        Public Shared ReadOnly Property ChannelNotFound() As String
            Get
                Return ResourceManager.GetString("ChannelNotFound", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to The channel topic was changed to:.
        '''</summary>
        Public Shared ReadOnly Property ChannelTopicChanged() As String
            Get
                Return ResourceManager.GetString("ChannelTopicChanged", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to The channel {oldName} was renamed to {newName}..
        '''</summary>
        Public Shared ReadOnly Property ChannelWasRenamed() As String
            Get
                Return ResourceManager.GetString("ChannelWasRenamed", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to That character is not logged on.  Try using *username to message a user or character@realm to message a character in a different realm..
        '''</summary>
        Public Shared ReadOnly Property CharacterNotLoggedOn() As String
            Get
                Return ResourceManager.GetString("CharacterNotLoggedOn", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to That command is not available at the moment..
        '''</summary>
        Public Shared ReadOnly Property ChatCommandUnavailable() As String
            Get
                Return ResourceManager.GetString("ChatCommandUnavailable", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Demoted {friend} down one level in your friends list..
        '''</summary>
        Public Shared ReadOnly Property DemotedFriend() As String
            Get
                Return ResourceManager.GetString("DemotedFriend", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Who do you want to demote?.
        '''</summary>
        Public Shared ReadOnly Property DemoteFriendEmptyTarget() As String
            Get
                Return ResourceManager.GetString("DemoteFriendEmptyTarget", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to {user} is your new designated heir..
        '''</summary>
        Public Shared ReadOnly Property DesignateCommand() As String
            Get
                Return ResourceManager.GetString("DesignateCommand", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to You have been disconnected by a system administrator..
        '''</summary>
        Public Shared ReadOnly Property DisconnectedByAdmin() As String
            Get
                Return ResourceManager.GetString("DisconnectedByAdmin", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Disconnected by Admin.
        '''</summary>
        Public Shared ReadOnly Property DisconnectedByAdminCaption() As String
            Get
                Return ResourceManager.GetString("DisconnectedByAdminCaption", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to You have been disconnected by a system administrator ({reason})..
        '''</summary>
        Public Shared ReadOnly Property DisconnectedByAdminWithReason() As String
            Get
                Return ResourceManager.GetString("DisconnectedByAdminWithReason", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Error.
        '''</summary>
        Public Shared ReadOnly Property ErrorCaption() As String
            Get
                Return ResourceManager.GetString("ErrorCaption", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Failed logon attempts since then: {count}.
        '''</summary>
        Public Shared ReadOnly Property FailedLogonAttempts() As String
            Get
                Return ResourceManager.GetString("FailedLogonAttempts", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Chatting with this game is restricted to the channels listed in the channel menu..
        '''</summary>
        Public Shared ReadOnly Property GameProductIsChatRestricted() As String
            Get
                Return ResourceManager.GetString("GameProductIsChatRestricted", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Advanced chat commands:
        '''/ban /beep /clan /designate /friends /kick /mail
        '''/nobeep /options /rejoin /stats /time /unban /users
        '''Type  /help COMMAND  for information about a specific command..
        '''</summary>
        Public Shared ReadOnly Property HelpCommandAdvancedRemarks() As String
            Get
                Return ResourceManager.GetString("HelpCommandAdvancedRemarks", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Command aliases:
        '''  /?         -- /help
        '''  /channel   -- /join
        '''  /squelch   -- /ignore
        '''  /whisper   -- /w /m /msg
        '''  /emote     -- /me
        '''  /rejoin    -- /resign
        '''  /unsquelch -- /unignore
        '''  /whois     -- /where /whereis
        '''  /friends   -- /f
        '''  /clan      -- /c
        '''Type  /help COMMAND  for information about a specific command..
        '''</summary>
        Public Shared ReadOnly Property HelpCommandAliasesRemarks() As String
            Get
                Return ResourceManager.GetString("HelpCommandAliasesRemarks", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to /ban USERNAME  (see also: /unban)
        '''(For channel Operators only) Bans a USERNAME from the channel, and prevents him from returning.
        '''Example: /ban JoeUser.
        '''</summary>
        Public Shared ReadOnly Property HelpCommandBanRemarks() As String
            Get
                Return ResourceManager.GetString("HelpCommandBanRemarks", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Basic chat commands:
        '''/away /dnd /channel /emote 
        '''/friends /options /squelch /unsquelch 
        '''/whisper /who /whoami /whois
        '''Type /help COMMAND for information about a specific command..
        '''</summary>
        Public Shared ReadOnly Property HelpCommandCommandsRemarks() As String
            Get
                Return ResourceManager.GetString("HelpCommandCommandsRemarks", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to /channel CHANNEL  (alias: /join)
        '''Moves you to a different CHANNEL.
        '''Example: /channel Blizzard Tech Support.
        '''</summary>
        Public Shared ReadOnly Property HelpCommandJoinRemarks() As String
            Get
                Return ResourceManager.GetString("HelpCommandJoinRemarks", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Battle.net help topics:
        '''commands  aliases  advanced
        '''Type /help TOPIC for information about a specific topic..
        '''</summary>
        Public Shared ReadOnly Property HelpCommandRemarks() As String
            Get
                Return ResourceManager.GetString("HelpCommandRemarks", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Battle.net help topics:
        '''commands  aliases  advanced
        '''Type /help TOPIC for information about a specific topic.
        '''Type /admin help for the administrator command list..
        '''</summary>
        Public Shared ReadOnly Property HelpCommandRemarksWithAdmin() As String
            Get
                Return ResourceManager.GetString("HelpCommandRemarksWithAdmin", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to /time
        '''Displays the current {realm} Time ({realmTimezone})..
        '''</summary>
        Public Shared ReadOnly Property HelpCommandTimeRemarks() As String
            Get
                Return ResourceManager.GetString("HelpCommandTimeRemarks", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to That is not a valid admin command. Type /admin help or /admin ? for more info..
        '''</summary>
        Public Shared ReadOnly Property InvalidAdminCommand() As String
            Get
                Return ResourceManager.GetString("InvalidAdminCommand", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Invalid channel name..
        '''</summary>
        Public Shared ReadOnly Property InvalidChannelName() As String
            Get
                Return ResourceManager.GetString("InvalidChannelName", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to That is not a valid command. Type /help or /? for more info..
        '''</summary>
        Public Shared ReadOnly Property InvalidChatCommand() As String
            Get
                Return ResourceManager.GetString("InvalidChatCommand", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Invalid user..
        '''</summary>
        Public Shared ReadOnly Property InvalidUser() As String
            Get
                Return ResourceManager.GetString("InvalidUser", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Last logon: {timestamp}.
        '''</summary>
        Public Shared ReadOnly Property LastLogonInfo() As String
            Get
                Return ResourceManager.GetString("LastLogonInfo", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to No one hears you..
        '''</summary>
        Public Shared ReadOnly Property NoOneHearsYou() As String
            Get
                Return ResourceManager.GetString("NoOneHearsYou", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Promoted {friend} up one level in your friends list..
        '''</summary>
        Public Shared ReadOnly Property PromotedFriend() As String
            Get
                Return ResourceManager.GetString("PromotedFriend", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Who do you want to promote?.
        '''</summary>
        Public Shared ReadOnly Property PromoteFriendEmptyTarget() As String
            Get
                Return ResourceManager.GetString("PromoteFriendEmptyTarget", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Removed {friend} from your friends list..
        '''</summary>
        Public Shared ReadOnly Property RemovedFriend() As String
            Get
                Return ResourceManager.GetString("RemovedFriend", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Who do you want to remove?.
        '''</summary>
        Public Shared ReadOnly Property RemoveFriendEmptyTarget() As String
            Get
                Return ResourceManager.GetString("RemoveFriendEmptyTarget", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to The server shutdown has been cancelled..
        '''</summary>
        Public Shared ReadOnly Property ServerShutdownCancelled() As String
            Get
                Return ResourceManager.GetString("ServerShutdownCancelled", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to The server shutdown has been cancelled ({message})..
        '''</summary>
        Public Shared ReadOnly Property ServerShutdownCancelledWithMessage() As String
            Get
                Return ResourceManager.GetString("ServerShutdownCancelledWithMessage", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to The server has been rescheduled for shutdown in {period}..
        '''</summary>
        Public Shared ReadOnly Property ServerShutdownRescheduled() As String
            Get
                Return ResourceManager.GetString("ServerShutdownRescheduled", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to The server has been rescheduled for shutdown in {period} ({message})..
        '''</summary>
        Public Shared ReadOnly Property ServerShutdownRescheduledWithMessage() As String
            Get
                Return ResourceManager.GetString("ServerShutdownRescheduledWithMessage", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to The server has been scheduled for shutdown in {period}..
        '''</summary>
        Public Shared ReadOnly Property ServerShutdownScheduled() As String
            Get
                Return ResourceManager.GetString("ServerShutdownScheduled", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to The server has been scheduled for shutdown in {period} ({message})..
        '''</summary>
        Public Shared ReadOnly Property ServerShutdownScheduledWithMessage() As String
            Get
                Return ResourceManager.GetString("ServerShutdownScheduledWithMessage", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to There are currently {gameUsers} users playing {gameAds} games of {game}, and {totalUsers} users playing {totalGameAds} games on {realm}..
        '''</summary>
        Public Shared ReadOnly Property ServerStatistics() As String
            Get
                Return ResourceManager.GetString("ServerStatistics", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to The Void.
        '''</summary>
        Public Shared ReadOnly Property TheVoid() As String
            Get
                Return ResourceManager.GetString("TheVoid", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to {realm} time: {realmTime}
        '''Your local time: {localTime}.
        '''</summary>
        Public Shared ReadOnly Property TimeCommand() As String
            Get
                Return ResourceManager.GetString("TimeCommand", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to {target} was banned by {source}.
        '''</summary>
        Public Shared ReadOnly Property UserBannedFromChannel() As String
            Get
                Return ResourceManager.GetString("UserBannedFromChannel", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to {target} was banned by {source} ({reason})..
        '''</summary>
        Public Shared ReadOnly Property UserBannedFromChannelWithReason() As String
            Get
                Return ResourceManager.GetString("UserBannedFromChannelWithReason", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to {target} is already banned from the channel!.
        '''</summary>
        Public Shared ReadOnly Property UserIsAlreadyBanned() As String
            Get
                Return ResourceManager.GetString("UserIsAlreadyBanned", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to {target} is not banned from the channel.
        '''</summary>
        Public Shared ReadOnly Property UserIsNotBanned() As String
            Get
                Return ResourceManager.GetString("UserIsNotBanned", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to {character}#{characterRealm} (*{username}) is using {game} in a private game..
        '''</summary>
        Public Shared ReadOnly Property UserIsUsingDiablo2InAPrivateGame() As String
            Get
                Return ResourceManager.GetString("UserIsUsingDiablo2InAPrivateGame", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to {username} is using {game} in a private game..
        '''</summary>
        Public Shared ReadOnly Property UserIsUsingGameInAPrivateGame() As String
            Get
                Return ResourceManager.GetString("UserIsUsingGameInAPrivateGame", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to {user} is using {game} in {realm}.
        '''</summary>
        Public Shared ReadOnly Property UserIsUsingGameInRealm() As String
            Get
                Return ResourceManager.GetString("UserIsUsingGameInRealm", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to {user} is using {game} in the channel {channel}..
        '''</summary>
        Public Shared ReadOnly Property UserIsUsingGameInTheChannel() As String
            Get
                Return ResourceManager.GetString("UserIsUsingGameInTheChannel", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to {username} is using {game} in game {gameAd}..
        '''</summary>
        Public Shared ReadOnly Property UserIsUsingGameInTheGame() As String
            Get
                Return ResourceManager.GetString("UserIsUsingGameInTheGame", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to {username} is using {game} in the password-protected game {gameAd}..
        '''</summary>
        Public Shared ReadOnly Property UserIsUsingGameInThePasswordedGame() As String
            Get
                Return ResourceManager.GetString("UserIsUsingGameInThePasswordedGame", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to {target} was kicked out of the channel by {source}..
        '''</summary>
        Public Shared ReadOnly Property UserKickedFromChannel() As String
            Get
                Return ResourceManager.GetString("UserKickedFromChannel", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to {target} was kicked out of the channel by {source} ({reason})..
        '''</summary>
        Public Shared ReadOnly Property UserKickedFromChannelWithReason() As String
            Get
                Return ResourceManager.GetString("UserKickedFromChannelWithReason", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to That user is not in a channel..
        '''</summary>
        Public Shared ReadOnly Property UserNotInChannel() As String
            Get
                Return ResourceManager.GetString("UserNotInChannel", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to That user is not logged on..
        '''</summary>
        Public Shared ReadOnly Property UserNotLoggedOn() As String
            Get
                Return ResourceManager.GetString("UserNotLoggedOn", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to {target} was unbanned by {source}.
        '''</summary>
        Public Shared ReadOnly Property UserUnBannedFromChannel() As String
            Get
                Return ResourceManager.GetString("UserUnBannedFromChannel", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to This server is running {version}..
        '''</summary>
        Public Shared ReadOnly Property VersionCommand() As String
            Get
                Return ResourceManager.GetString("VersionCommand", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to This server is running {version}.
        '''Node uptime: {systemUptime}
        '''Process uptime: {processUptime}.
        '''</summary>
        Public Shared ReadOnly Property VersionCommandWithAdmin() As String
            Get
                Return ResourceManager.GetString("VersionCommandWithAdmin", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to What do you want to say?.
        '''</summary>
        Public Shared ReadOnly Property WhisperCommandEmptyMessage() As String
            Get
                Return ResourceManager.GetString("WhisperCommandEmptyMessage", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to {user} is away ({message}).
        '''</summary>
        Public Shared ReadOnly Property WhisperCommandUserIsAway() As String
            Get
                Return ResourceManager.GetString("WhisperCommandUserIsAway", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to {user} is unavailable ({message}).
        '''</summary>
        Public Shared ReadOnly Property WhisperCommandUserIsDoNotDisturb() As String
            Get
                Return ResourceManager.GetString("WhisperCommandUserIsDoNotDisturb", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Users in channel {channel}:
        '''{users}.
        '''</summary>
        Public Shared ReadOnly Property WhoCommand() As String
            Get
                Return ResourceManager.GetString("WhoCommand", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to You are banned from that channel..
        '''</summary>
        Public Shared ReadOnly Property YouAreBannedFromThatChannel() As String
            Get
                Return ResourceManager.GetString("YouAreBannedFromThatChannel", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to You are not a channel operator..
        '''</summary>
        Public Shared ReadOnly Property YouAreNotAChannelOperator() As String
            Get
                Return ResourceManager.GetString("YouAreNotAChannelOperator", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to You are {name}, using {game} in game {gameAd}..
        '''</summary>
        Public Shared ReadOnly Property YouAreUsingGameInGame() As String
            Get
                Return ResourceManager.GetString("YouAreUsingGameInGame", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to You are {name}, using {game} in {realm}.
        '''</summary>
        Public Shared ReadOnly Property YouAreUsingGameInRealm() As String
            Get
                Return ResourceManager.GetString("YouAreUsingGameInRealm", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to You are {name}, using {game} in the channel {channel}..
        '''</summary>
        Public Shared ReadOnly Property YouAreUsingGameInTheChannel() As String
            Get
                Return ResourceManager.GetString("YouAreUsingGameInTheChannel", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to You can&apos;t ban a channel operator..
        '''</summary>
        Public Shared ReadOnly Property YouCannotBanAChannelOperator() As String
            Get
                Return ResourceManager.GetString("YouCannotBanAChannelOperator", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to You can&apos;t kick a channel operator..
        '''</summary>
        Public Shared ReadOnly Property YouCannotKickAChannelOperator() As String
            Get
                Return ResourceManager.GetString("YouCannotKickAChannelOperator", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Your friend {friend} has entered a {game} game called {gameAd}..
        '''</summary>
        Public Shared ReadOnly Property YourFriendEnteredGame() As String
            Get
                Return ResourceManager.GetString("YourFriendEnteredGame", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Your friend {friend} has entered a password-protected {game} game called {gameAd}..
        '''</summary>
        Public Shared ReadOnly Property YourFriendEnteredPasswordedGame() As String
            Get
                Return ResourceManager.GetString("YourFriendEnteredPasswordedGame", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Your friend {friend} has exited {realm}..
        '''</summary>
        Public Shared ReadOnly Property YourFriendLoggedOff() As String
            Get
                Return ResourceManager.GetString("YourFriendLoggedOff", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Your friend {friend} has entered {realm}..
        '''</summary>
        Public Shared ReadOnly Property YourFriendLoggedOn() As String
            Get
                Return ResourceManager.GetString("YourFriendLoggedOn", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to Your friends list:.
        '''</summary>
        Public Shared ReadOnly Property YourFriendsList() As String
            Get
                Return ResourceManager.GetString("YourFriendsList", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to {source} banned you from the channel!.
        '''</summary>
        Public Shared ReadOnly Property YouWereBannedFromChannel() As String
            Get
                Return ResourceManager.GetString("YouWereBannedFromChannel", resourceCulture)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized string similar to {source} kicked you out of the channel!.
        '''</summary>
        Public Shared ReadOnly Property YouWereKickedFromChannel() As String
            Get
                Return ResourceManager.GetString("YouWereKickedFromChannel", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
