name: .NET

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-atlasd:
    name: Build Atlasd

    runs-on: ubuntu-latest
    env:
      working-directory: ./src/Atlasd

    steps:
    - uses: actions/checkout@v4
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'
    - name: Install dependencies
      run: dotnet restore
      working-directory: ${{env.working-directory}}
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ${{env.working-directory}}
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: ${{env.working-directory}}
